FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_COMPILE_BYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /workspace
COPY . .
RUN uv sync --frozen --no-dev --package __NAME__
ENV PATH="/workspace/.venv/bin:$PATH"
WORKDIR /workspace/apps/__NAME__
CMD ["python", "-m", "__PKG__.main"]
